topic:
  name: "t1_benchmark"
  replicationFactor: 3
  partitions: 1

broker:
  url: "pkc-6ojv2.us-west4.gcp.confluent.cloud:9092"
  username: "NU6OWKGDHI4HPWWU"
  password: "fA/SbrrzjqPJ/KHRdey1Icq+VcP0n30dKGhmZ8xNli9a/Vpctgxx/vwaKl+e25FR"

producer:
  enabled: true
  image: "confluentinc/cp-kafka:7.0.1"
  recordsCount: 1000
  recordSizeBytes: 1024
  throughput: "-1"
  acks: 1
  count: 3
  params: "batch.size=100000 linger.ms=100 compression.type=lz4"

consumer:
  enabled: true
  image: "confluentinc/cp-kafka:7.0.1"
  messagesCount: 1000
  count: 1
  timeout: 100000

e2e:
  enabled: false
  image: "confluentinc/cp-kafka:7.0.1"
  recordsCount: 1000
  recordSizeBytes: 1024
  acks: "all"

kubePrometheus:
  enabled: true

# values for kube-prometheus-stack subchart
kube-prometheus-stack:
  grafana:
    adminPassword: platformatory

prometheus:
  remote_write:
  - url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/prometheus/v1/write"
# Example for New Relic
  # - url: https://metric-api.newrelic.com/prometheus/v1/write?prometheus_server=kafka-perf-test
  #   bearer_token: xxxxxxxxxxxxxxxxxxxxxxxxxxx
