{{- if .Values.consumer.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "confluent-performance-suite.fullname" . }}-consumer-{{ .Release.Revision }}"
  labels:
    {{- include "confluent-performance-suite.labels" . | nindent 4 }}
  annotations:
    timestamp: {{ now | quote }}
spec:
  completions: {{ .Values.consumer.count }}
  parallelism: {{ .Values.consumer.count }}
  template:
    spec:
      initContainers:
      - name: topics
        image: {{ .Values.consumer.image }}
        command:
        - /bin/sh
        - -c
        - |
          kafka-topics \
            --if-not-exists \
            --topic {{ .Values.topic.name }}  \
            --create \
            --bootstrap-server {{ .Values.broker.url }} \
            --replication-factor {{ .Values.topic.replicationFactor }}  \
            --partitions {{ .Values.topic.partitions }}  \
            --command-config /mnt/kafka.properties
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
      containers:
      - name: consumer
        image: {{ .Values.consumer.image }}
        command:
        - /bin/sh
        - -c
        - |
          (./prometheus --enable-feature=agent --config.file="/prom/prometheus.yml" --log.level=error & ) && \
          kafka-consumer-perf-test \
            --topic {{ .Values.topic.name }}  \
            --bootstrap-server {{ .Values.broker.url }} \
            --messages {{ .Values.consumer.messagesCount }} \
            --consumer.config /mnt/kafka.properties \
            --timeout {{ .Values.consumer.timeout }}
        env:
        - name: KAFKA_OPTS
          value: -javaagent:/usr/app/jmx_prometheus_javaagent-0.15.0.jar=7071:/usr/app/kafka_client.yml
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
        - name: prometheus-config
          mountPath: /prom
      volumes:
        - name: kafka-properties
          secret:
            secretName: "{{ include "confluent-performance-suite.fullname" . }}-kafka-client-config"
        - name: prometheus-config
          configMap:
            name: "{{ include "confluent-performance-suite.fullname" . }}-prometheus-config"
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
