{{- if .Values.e2e.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "confluent-performance-suite.fullname" . }}-e2e-{{ .Release.Revision }}"
  labels:
    {{- include "confluent-performance-suite.labels" . | nindent 4 }}
  annotations:
    timestamp: {{ now | quote }}
spec:
  template:
    spec:
      initContainers:
      - name: topics
        image: {{ .Values.e2e.image }}
        command:
        - /bin/sh
        - -c
        - |
          kafka-topics \
            --if-not-exists \
            --topic {{ .Values.topic.name }}  \
            --create \
            --bootstrap-server {{ .Values.broker.url }} \
            --replication-factor {{ .Values.topic.replicationFactor }}  \
            --partitions {{ .Values.topic.partitions }}  \
            --command-config /mnt/kafka.properties
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
      containers:
      - name: e2e
        image: {{ .Values.e2e.image }}
        command:
        - /bin/sh
        - -c
        - |
          kafka-run-class kafka.tools.EndToEndLatency {{ .Values.broker.url }} {{ .Values.topic.name }} {{ .Values.e2e.recordsCount }} {{ .Values.e2e.acks }} {{ .Values.e2e.recordSizeBytes }} /mnt/kafka.properties
        env:
        - name: KAFKA_OPTS
          value: -javaagent:/usr/app/jmx_prometheus_javaagent-0.15.0.jar=7071:/usr/app/kafka_client.yml
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
      volumes:
        - name: kafka-properties
          secret:
            secretName: "{{ include "confluent-performance-suite.fullname" . }}-kafka-client-config"
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
