apiVersion: v1
data:
  kafka.properties: {{ tpl (.Files.Get "conf/kafka.properties") . | b64enc }}
kind: Secret
metadata:
  name: "{{ include "confluent-performance-suite.fullname" . }}-kafka-client-config"
  labels:
    {{- include "confluent-performance-suite.labels" . | nindent 4 }}
type: Opaque
