apiVersion: v1
data:
  kafka.properties: {{ tpl (.Files.Get "conf/kafka.properties") . | b64enc }}
kind: Secret
metadata:
  name: "{{ include "kafka-performance-metrics.fullname" . }}-kafka-client-config"
  labels:
    {{- include "kafka-performance-metrics.labels" . | nindent 4 }}
type: Opaque
