topic:
  name: "t1_benchmark"
  replicationFactor: 3
  partitions: 1

broker:
  url: "pkc-6ojv2.us-west4.gcp.confluent.cloud:9092"
  username: "JR7J4VZD3QZRWZHF"
  password: "nt18VXlr6awSrSif85C8Q+Lq7BVgIrfQPmjkqEQvLVsro1y9Apqjf9UwuLieBgdu"

producer:
  enabled: true
  image: "lakshminp/kafka:30-03-2023.1"
  recordsCount: 10000
  recordSizeBytes: 1024
  throughput: "-1"
  acks: 1
  count: 1
  params: "batch.size=100 linger.ms=100 compression.type=lz4"

consumer:
  enabled: false
  image: "lakshminp/kafka:30-03-2023.1"
  messagesCount: 10000
  count: 1
  timeout: 100000

e2e:
  enabled: false
  image: "lakshminp/kafka:30-03-2023.1"
  recordsCount: 1000
  recordSizeBytes: 1024
  acks: "all"

prometheus:
  remote_write:
  - url: "http://prom-stack-kube-prometheus-prometheus:9090/api/v1/write"
# Example for New Relic
  # - url: https://metric-api.newrelic.com/prometheus/v1/write?prometheus_server=kafka-perf-test
  #   bearer_token: xxxxxxxxxxxxxxxxxxxxxxxxxxx
